### ISSUE TITLE
Longueur de champs tickets_id

### ISSUE THREAD

**Issue by jmdadolle** [pluginsGLPI/credit#1]
Dans la table glpi_plugin_credit_tickets le champs tickets_id est créé en TINYINT alors que le champs correspondant dans la table tickets est en INT(11).
Dès que l'on dépasse les 127 tickets le ticket numéro 127 est systématiquement affecté dans le détail des crédits consommés.

**Comment by flegastelois** [comment]
Bonjour @jmdadolle ,
Merci pour votre retour ! La version 1.0.1 corrige ce bug.
François.
