### ISSUE TITLE
Errors with Travis CI in project site

### ISSUE THREAD

**Issue by Naylin15** [pluginsGLPI/credit#19]
#### Observed Results
Html proofer found 32 failures while running the tests

  Ref [Travis CI Output](https://travis-ci.org/pluginsGLPI/credit/builds/371752311?utm_source=github_status&utm_medium=notification)

#### Expected behavior

To fix these failures

**Comment by ajsb85** [comment]
Hi, @Naylin15 
There are a lot of warnings of css, you should request this hotfix from @e1matheus

**Comment by Naylin15** [comment]
Other Ref: [#56](https://github.com/pluginsGLPI/sccm/pull/56)

**Comment by Naylin15** [comment]
Update:

Following this issue [#376](https://github.com/gjtorikian/html-proofer/issues/376) and adding these lines as indicated to the .travis.yml file 
```
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
```
Fixed the errors with html proofer regarding SSL

Tested on my fork of credit's repo

[Succesfull check on Travis](https://travis-ci.org/Naylin15/credit/builds/372696648)

I'll test it in other forks of Flyve MDM before making the PR with the fix

**Comment by Naylin15** [comment]
Update:

The lines fixed the failures regarding SSL in other forks too

[Errors on ios-mdm-dashboard](https://travis-ci.org/Naylin15/ios-mdm-dashboard/builds/373096904)
[Succesful check](https://travis-ci.org/Naylin15/ios-mdm-dashboard/builds/373098468)

I'll be making the fixes to close this issue

**Comment by Naylin15** [comment]
The failures were fixed, this issue can be closed

- [SCCM build](https://travis-ci.org/pluginsGLPI/sccm/builds/373113889?utm_source=github_status&utm_medium=notification)
- [Mantis build](https://travis-ci.org/pluginsGLPI/mantis/builds/373110246?utm_source=github_status&utm_medium=notification)
- [Credit build](https://travis-ci.org/pluginsGLPI/credit/builds/373107655?utm_source=github_status&utm_medium=notification)
