### ISSUE TITLE
Credit consume (French)

### ISSUE THREAD

**Issue by aze789** [pluginsGLPI/credit#26]
Bonjour,
j'aimerais savoir comment faire pour que les credits soit consommer et ainsi afficher leur quantite dans l'onglet Crédit.
Merci

**Comment by cedric-anne** [comment]
Hi,

To be able to consume credits, you have to:
- create `Credit vouchers types` in `Setup > Dropdowns > Credit vouchers types` page (`plugins/credit/front/type.php`),
- add a credit voucher for your entity using the `Credit coucher` tab of the entity accessible in `Administration > Entities`.
After doing this, you should be able to consume credits when submitting a solution to your tickets.

Regard

**Comment by aze789** [comment]
thx but how can I declare a credit pls ??

**Comment by cedric-anne** [comment]
Hi,

I already answer to this in my previous comment.

1) Have you create a `Credit voucher type` in `Setup > Dropdowns > Credit vouchers types` ?
2) Have add a `Credit voucher`  for your entity using the `Credit coucher` tab of the entity accessible in `Administration > Entities` ?
3) Is your ticket related to the entity on which you add a credit ?

If you have done this, you should see related fields in ticket solution form.

Regards

**Comment by aze789** [comment]
Yeah already creat all that and when I click in the consume quantity I got this 
![image](https://user-images.githubusercontent.com/39768717/40841105-944d507a-65a9-11e8-9a5f-fb502bca81bf.png)

**Comment by aze789** [comment]
Yeah already creat all that and when I click in the consume quantity I got this

![image](https://user-images.githubusercontent.com/39768717/40841160-bfcc4bb6-65a9-11e8-8467-2199157937b6.png)

**Comment by cedric-anne** [comment]
If you have this, then you should be able to consume credits when submitting a solution to the ticket.

You can access to the ticket solution form by clicking (1) then (2) as shown in below image. Then credits fields should be visible (3).
![consume_credits](https://user-images.githubusercontent.com/33253653/40841781-f43d36f6-65ab-11e8-8c7c-df434ef0da3a.png)

**Comment by aze789** [comment]
yeah that what I was looking for :) Thank you for you help man
