### ISSUE TITLE
Utilisateur déclarant

### ISSUE THREAD

**Issue by gfoujanet** [pluginsGLPI/credit#46]
#### Observed Results
GLPI est organisé par entités.
L'utilisateur déclarant est toujours le même quelque soit le ticket observé (un utilisateur lambda).
  
#### Expected behavior
Voir le déclarant dans le champs "Utilisateur déclarant"

**Comment by gfoujanet** [comment]
Après vérifications dans la base, dans la table "glpi_plugin_credit_tickets" tous les champs "users_id" portent la valeur 127 qui est un utilisateur lambda d'une entité qui n'a dans les faits qu'un ou deux tickets associés.

**Comment by stonebuzz** [comment]
Hi @gfoujanet 

can you test latest version, this problem is fix.

Best regards.
