### ISSUE TITLE
Fonctionnement plugin

### ISSUE THREAD

**Issue by kitein44** [pluginsGLPI/credit#50]
Bonjour,

J'aurais voulu savoir comment le plugin fonctionne:
Comment crédite t'il du temps sur un ticket? Lors d'un ticket clos, résolu? 
Comment créditer du temps manuellement?
Y a t-il un Wiki car le lien vers la documentation est mort?

Merci a vous,

Quentin

**Comment by stonebuzz** [comment]
Hi @kitein44 

you can find latest documentation here -> https://glpi-plugins.readthedocs.io/en/master/credit/index.html

I am closing this issue, feel free to continue the discussion here if you want.

Best regards
