### ISSUE TITLE
PHP Fatal Error sur MAJ 1.0.1 -> 1.1.0

### ISSUE THREAD

**Issue by dedisoft** [pluginsGLPI/credit#8]
Bonjour,

Lors de la mise à niveau du plugin (1.01 vers 1.1.0) sous GLPI 9.2, erreur PHP (7.0) :

  thrown in /inc/dbmysql.class.php on line 729
[28-Sep-2017 10:30:44 Europe/Berlin] PHP Fatal error:  Uncaught Error: Using $this when not in object context in /inc/dbmysql.class.php:729
Stack trace:
#0 plugins/credit/inc/entity.class.php(350): DBmysql::tableExists('glpi_plugin_cre...')
#1 plugins/credit/hook.php(46): PluginCreditEntity::install(Object(Migration))
#2 inc/plugin.class.php(730): plugin_credit_install()
#3 front/plugin.form.php(48): Plugin->install('7')
#4 {main}
  thrown in inc/dbmysql.class.php on line 729

Cordialement,

**Comment by grego1981** [comment]
Same error when trying uprade on same environment 9.2 and PHP 7.0

**Comment by lordkaisernosferat** [comment]
Salut, même erreur pour moi sur une install toute neuve de GLPI 9.2 + php7 + credits 1.1.0
Cordialement,
K

**Comment by grego1981** [comment]
For the installation part, I found a way to at least install it just replace !$DB::tableExists($table) with !$DB->tableExists($table) in files inc/entity.class.php 350 - inc/ticket.class.php 539 - inc/type.class.php 53

Tables get created OK but no front end to add credit vouchers also when trying to add one from the ticket solution form I get the error
>script '/var/www/html/glpi/plugins/credit/front/entity.php' not found or unable to stat

in fact such a file does not exist in the front folder.

**Comment by flegastelois** [comment]
Hi all,
This bug is already fixed by https://github.com/pluginsGLPI/credit/pull/7
It will be included in version 1.1.1.
Regards
